NAME = riot.dll
CC = CL.EXE
LINKER = LINK.EXE
CFLAGS = /W3 /WX /WL /O2 /TP /MT /c\
/D SOURCEMM_EXPORTS /D _USRDLL /D _MBCS\
/D _CRT_SECURE_NO_DEPRECATE /D _CRT_SECURE_NO_WARNINGS /D _CRT_NONSTDC_NO_DEPRECATE\
/D SE_EPISODEONE=1 /D SE_DARKMESSIAH=2 /D SE_ORANGEBOX=3\
/D SE_BLOODYGOODTIME=4 /D SE_EYE=5 /D SE_CSS=6 /D SE_ORANGEBOXVALVE=7\
/D SE_LEFT4DEAD=8 /D SE_LEFT4DEAD2=9 /D SE_ALIENSWARM=10\
/D SE_PORTAL2=11 /D SE_CSGO=12\
/D SOURCE_ENGINE=1\
/D WIN32 /D _WINDOWS
LFLAGS = /DLL\
/MACHINE:X86\
/SUBSYSTEM:WINDOWS\
/NODEFAULTLIB:LIBC;LIBCD;LIBCMTD\
/LIBPATH:$(HL2SDK)\lib\public\
/DYNAMICBASE:NO\
/INCREMENTAL:NO\
/LTCG\
/MANIFEST\
/MANIFESTUAC:"uiAccess='false' level='asInvoker'"\
/OPT:REF\
/OPT:ICF\

SRCS_PATH = srcs
OBJS_PATH = objs
INCLUDES_PATH = includes
BUILD_PATH = build

INCLUDES = $(INCLUDES_PATH)\
$(MMSOURCE18)\core\
$(MMSOURCE18)\core\sourcehook\
$(HL2SDK)\public\
$(HL2SDK)\public\dlls\
$(HL2SDK)\public\engine\
$(HL2SDK)\public\game\server\
$(HL2SDK)\public\tier0\
$(HL2SDK)\public\tier1\
$(HL2SDK)\public\vstdlib\

LIBS = tier0.lib tier1.lib vstdlib.lib legacy_stdio_definitions.lib

SRCS_FILES = \riot.x \day.x \zombie.x

SINGLESPACE=$(subst ',,' ')

OBJS = $(subst \,$(OBJS_PATH)\,$(SRCS_FILES))
OBJS = $(subst .x,.obj,$(OBJS))
SRCS = $(subst \,$(SRCS_PATH)\,$(SRCS_FILES))
SRCS = $(subst .x,.cpp,$(SRCS))
INCLUDES = $(subst $(SINGLESPACE),;,$(INCLUDES))

INCLUDE = $(INCLUDES);$(INCLUDE)

all: $(SRCS) $(OBJS_PATH) $(BUILD_PATH) $(NAME)

$(OBJS_PATH):
	MD objs

$(BUILD_PATH):
	MD build

$(OBJS): $(SRCS)
	$(CC) /Fo$(OBJS_PATH)\ $(CFLAGS) $(SRCS)

$(NAME): $(OBJS)
	$(LINKER) /OUT:$(BUILD_PATH)\$(NAME) $(LFLAGS) $(OBJS) $(LIBS)

clean:
	!IF EXIST "$(OBJS_PATH)" RMDIR /s /q $(OBJS_PATH)

fclean: clean
	!IF EXIST "$(BUILD_PATH)" RMDIR /s /q $(BUILD_PATH)

re: fclean all